module.exports = [
  "amater",
  "društvena igra",
  "nalet",
  "tren",
  "upala",
  "sićušno",
  "klizna vrata",
  "kuharica",
  "oklevetati",
  "nosnica",
  "štala",
  "zglob",
  "šareno",
  "kapak",
  "cilindar",
  "plaža",
  "modrica",
  "inflacija",
  "igračka",
  "izdajica",
  "požar",
  "polje",
  "bongo bubanj",
  "žrtva",
  "ćevapčići",
  "tema",
  "spasilac",
  "brzinomjer",
  "posjetnica",
  "marmelada",
  "straćara",
  "oteti",
  "domaća mačka",
  "potomak",
  "pitati",
  "znojno",
  "Beverly Hills",
  "glazbeni video",
  "vodica za ispiranje usta",
  "savjetnik",
  "kopirati",
  "hvatanje",
  "dvokolica",
  "ujak",
  "urlik",
  "lakat",
  "zaleđivanje",
  "hokej na ledu",
  "ruševine",
  "New York",
  "poruka",
  "špijunaža",
  "prekršaj",
  "odvijač",
  "skitnica",
  "kasica prasica",
  "trening",
  "pročistiti",
  "zamka",
  "napjev",
  "dnevnik",
  "potraživanje",
  "ribar",
  "lančana reakcija",
  "starija osoba",
  "tegliti",
  "željan",
  "jastučnica",
  "ruksak",
  "obitelj",
  "nizbrdo",
  "plamenac",
  "zavod",
  "embargo",
  "umjetnost",
  "palica",
  "pirjati",
  "spavaćica",
  "kitova pjesma",
  "vojnik",
  "moćno",
  "periskop",
  "kapuljača",
  "strpljenje",
  "čajna žličica",
  "križarski ratovi",
  "superiornost",
  "kritičan",
  "mliječni napitak",
  "skijaška staza",
  "humanoid",
  "hibernirati",
  "Portugal",
  "prometnik",
  "prometna nesreća",
  "pojaviti",
  "NLO",
  "fotokopirna mašina",
  "optički",
  "hard disk",
  "neskladno",
  "McDonald’s",
  "zupčanik",
  "šuplje",
  "zanositi",
  "prskati",
  "Geigerov brojač",
  "jasika",
  "tigar",
  "morska bolest",
  "grlobolja",
  "spužva",
  "bikini",
  "atom",
  "istraživač",
  "upravljač",
  "bič",
  "bankovni račun",
  "cipli",
  "sitničar",
  "nerealno",
  "pseća hrana",
  "pčela",
  "pojedinac",
  "nacionalno",
  "razbojnik",
  "nosorog",
  "brak",
  "sjekira",
  "trajekt",
  "Pozdrav suncu",
  "sestra",
  "zasjeniti",
  "dizalica",
  "marka",
  "japanski",
  "režati",
  "Kanada",
  "Jo-jo",
  "memorijska kartica",
  "mornar",
  "Kip slobode",
  "indikator",
  "rezultat",
  "trulež",
  "Sahara",
  "praznik",
  "pagansko",
  "vijak",
  "zračna luka",
  "zvjezdano nebo",
  "suvišak",
  "plastična folija",
  "bodež",
  "novčić",
  "stručna knjiga",
  "suho",
  "primalja",
  "korak",
  "kava s mlijekom",
  "talac",
  "pećina",
  "glazura",
  "jednosmjerna karta",
  "junak",
  "konjica",
  "rupčić",
  "fatalan",
  "kotao",
  "kalup",
  "drhtati",
  "ležaljka",
  "mamut",
  "konj",
  "trombon",
  "usko grlo",
  "harfa",
  "kockasto",
  "drveno",
  "čvor",
  "indijac",
  "uloga",
  "grablje",
  "leglo",
  "E-mail",
  "odluka",
  "eskim",
  "list",
  "zglavci",
  "puls",
  "sirena",
  "uš",
  "pletenice",
  "lebdjeti",
  "sluh",
  "harmonikaš",
  "probisvjet",
  "peći",
  "nasilnik",
  "industrijski posjed",
  "tlo",
  "plačljivko",
  "dvojezično",
  "hrkanje",
  "pored",
  "krumipiršte",
  "kondukter",
  "svinja",
  "slamarica",
  "koštana srž",
  "motel",
  "Španjolska",
  "prirodno",
  "kandidat",
  "vrh nosa",
  "valcer",
  "lepršanje",
  "badminton",
  "biciklist",
  "pljačka",
  "džepar",
  "zakopati",
  "zvižduk",
  "ruža",
  "dijete",
  "zuriti",
  "parfem",
  "John Lennon",
  "sinonim",
  "ušećerena jabuka",
  "broš",
  "podsvjesno",
  "Rim",
  "kredit",
  "ispod",
  "Drava",
  "gusto",
  "biljar",
  "šljiva",
  "munja",
  "nordijsko hodanje",
  "perilica rublja",
  "ura",
  "trzaj",
  "siroče",
  "siva",
  "simfonija",
  "sjekirom u med",
  "akt",
  "top model",
  "salsa",
  "kombajn",
  "rap",
  "sanjke",
  "harmonika",
  "kruna",
  "nagnuto",
  "latinski",
  "Šiljo",
  "svađa",
  "serenada",
  "ljetovanje",
  "cijev",
  "propovijed",
  "izolirati",
  "grickati",
  "zatvor",
  "djetelina s četiri lista",
  "gutač vatre",
  "plavetni kit",
  "ravno",
  "čestitati",
  "grill trava",
  "prvorođenac",
  "prosjek",
  "iverak",
  "ovalno",
  "letjeti",
  "suze",
  "palma",
  "pitanje",
  "strah",
  "otkrhnuti",
  "Arktički ocean",
  "suvenir",
  "zadivljeno",
  "perec",
  "potisnuti",
  "ljubimac",
  "higijena",
  "harpun",
  "tišina",
  "lansiranje",
  "kuna zlatica",
  "Pariz",
  "čarobnjak",
  "kuhati",
  "geometrija",
  "skliznuti",
  "vremenske prilike",
  "narukvice za plivanje",
  "upravni odbor",
  "sunčanje",
  "Batman",
  "gornja usna",
  "ukleta kuća",
  "gravura",
  "američki nogomet",
  "klub",
  "park za pse",
  "smeće",
  "simbol",
  "skok",
  "fotografirati",
  "Hindu",
  "Oltar domovine",
  "patka",
  "karta za vlak",
  "zimske čizme",
  "pramac",
  "sorbet",
  "gristi",
  "filmsko platno",
  "prase",
  "gumena patkica",
  "smreka",
  "tajno društvo",
  "baciti",
  "lak za kosu",
  "marcipan",
  "termometar",
  "vunene čarape",
  "pokisnuti",
  "luksuz",
  "pasta za zube",
  "kliziti",
  "slavoluk",
  "ručnik",
  "pješak",
  "pilot",
  "rijetko",
  "Briljantin",
  "brijaći aparat",
  "teren",
  "vrećica čaja",
  "jedrilica",
  "maćeha",
  "bečki odrezak",
  "sobni bicikl",
  "živac",
  "vješalica",
  "tortica",
  "olakšati",
  "kriket",
  "turpija za nokte",
  "Pltvička jezera",
  "sredstva",
  "izlaz",
  "grbavac",
  "plovak",
  "mehaničar",
  "violončelo",
  "pelikan",
  "gumbi za manšetu",
  "skakavac",
  "akvarij",
  "egipćanin",
  "vegetarijanac",
  "ljudski",
  "kanadsko",
  "zabrana",
  "slomljeno",
  "štrumpf",
  "karavan",
  "sovjetski savez",
  "lopta za plažu",
  "izložba",
  "igla",
  "mjehurić",
  "jabuka",
  "naivno",
  "vrtuljak",
  "oženiti se",
  "general",
  "Beatlesi",
  "dnevno svjetlo",
  "mrak",
  "kopačke",
  "slavina",
  "lopata za snijeg",
  "razmjena",
  "ovca",
  "aparat za zavarivanje",
  "tkati",
  "knjićničar",
  "grad",
  "klaun",
  "prosjak",
  "zaposlenik",
  "pametno",
  "podmornica",
  "klizati",
  "uzorak",
  "uzorak",
  "Švicarska",
  "publika",
  "žohar",
  "hendikep",
  "rođendan",
  "natrag",
  "sapunica",
  "električni automobil",
  "ljepljiva traka",
  "aktivist",
  "Hrvatska",
  "kočnica za slučaj opasnosti",
  "ledolomac",
  "nemilosrdan",
  "božićni ukrasi",
  "turban",
  "ilustracija",
  "srca",
  "nadnica",
  "roštilj",
  "iskra",
  "ugljikohidrati",
  "mjehur",
  "anonimno",
  "kora",
  "stres",
  "stručnjak",
  "grejp",
  "grudnjak",
  "vodotoranj",
  "ručni zglob",
  "posljednji",
  "blues",
  "pisati",
  "miš",
  "tango",
  "djevojčica",
  "faraon",
  "pokušati",
  "usporiti",
  "smanjiti",
  "vagati",
  "prašuma",
  "ispariti",
  "Pero Kvržica",
  "krštenje",
  "dabar",
  "Valentinovo",
  "izazvati",
  "molekula",
  "dva",
  "suprug",
  "guru",
  "grmljavina",
  "opasno",
  "galeb",
  "ledenjak",
  "plesati",
  "nakovrčati",
  "dina",
  "vaga",
  "u sitne sate",
  "nevidljivo",
  "obrazac",
  "fotograf",
  "vinska čaša",
  "gladijator",
  "ateist",
  "uznemiravati",
  "trgovački centar",
  "crna magija",
  "cimbalo",
  "obrve",
  "želudac",
  "promil",
  "smjestiti",
  "čimpanza",
  "odraslo",
  "smoking",
  "pregača",
  "lisica",
  "ogrtač",
  "čamac",
  "listopad",
  "jamstvo",
  "žudjeti",
  "časnik",
  "vi",
  "sjaj",
  "čavka",
  "dom",
  "teret",
  "naljutiti",
  "kroz",
  "stomatolog",
  "Gospodar prstenova",
  "horizont",
  "prugasto",
  "potkova",
  "potresti",
  "pamuk",
  "lisnato tijesto",
  "skejbord",
  "kormilo",
  "remen",
  "dvoransko plesanje",
  "utopiti",
  "krvnik",
  "pas lutalica",
  "vatrogasni aparat",
  "poveznica",
  "akumulator",
  "tisak",
  "benzin",
  "bankomat",
  "sirup",
  "kletva",
  "živica",
  "unutar",
  "vodeni pištolj",
  "vriska",
  "strmo",
  "melodija",
  "manijak",
  "kanarinac",
  "račun",
  "zamorno",
  "zamoriti se",
  "planet",
  "dukat",
  "dnevna soba",
  "laž",
  "vaše",
  "preuređivanje",
  "Alladin",
  "pozornica",
  "pivski trbuh",
  "uznemirano",
  "kružno putovanje",
  "kaseta",
  "div",
  "kauboj",
  "kremasti sladoled",
  "crno vino",
  "figura",
  "vračara",
  "metar",
  "srebrna žlica",
  "perika",
  "ždrijebe",
  "šupljina",
  "dodir",
  "sjajno",
  "crtati",
  "kiselo",
  "crvenkasto",
  "solist",
  "Pipi Duga Čarapa",
  "kroasan",
  "ubrzati",
  "uvenuti",
  "valjak za tijesto",
  "kuća",
  "crveno",
  "tanker",
  "halapljivo",
  "priroda",
  "konkavan",
  "opozicija",
  "lijepo",
  "krletka",
  "snjegović",
  "grah",
  "ružno",
  "Gornji grad",
  "čudno",
  "lutka",
  "kockice",
  "promukao",
  "rijeka",
  "sići",
  "galop",
  "podmazati",
  "festival",
  "slušalice",
  "orah",
  "izbjegavati",
  "brnjica",
  "vuk",
  "obojeno",
  "plastični kirug",
  "prokuhati",
  "termosica",
  "kad",
  "farmaceut",
  "vratar",
  "pauza",
  "grba",
  "zvijezda padalica",
  "fanfare",
  "stražnje sjedalo",
  "podjela",
  "vjetroturbina",
  "kvadrat",
  "more",
  "Crveni križ",
  "panoramski kotač",
  "ograničiti",
  "bubamara",
  "ispucano",
  "nezemaljsko",
  "strašilo",
  "zmija otrovnica",
  "crna rupa",
  "labud",
  "kubik",
  "disk",
  "krpa",
  "grčki",
  "mjehuričasti omot",
  "Dan očeva",
  "gorko",
  "biceps",
  "nastaviti",
  "zlatna ribica",
  "elastično",
  "grickalice",
  "ponoć",
  "žarko",
  "Egipat",
  "rešetka",
  "nagrada",
  "karamela",
  "zračni jastuk",
  "bubnjar",
  "popodnevni čaj",
  "ručak",
  "rektor",
  "zvonik",
  "njihov",
  "kasino",
  "trol",
  "krojač",
  "odskakivati",
  "crtež",
  "zaporka",
  "zeleno",
  "budilica",
  "gurnuti",
  "kamera",
  "nošeno",
  "čudovište",
  "režanje",
  "kukac",
  "razmaženo",
  "lavež",
  "aukcija",
  "pauk",
  "ljuljačka",
  "čarape",
  "luk",
  "visoko",
  "ljestvica",
  "skladište",
  "sudac",
  "kipar",
  "terensko vozilo",
  "san",
  "odoljeti",
  "ekipa",
  "spustiti se",
  "skuter",
  "uspjeh",
  "poster",
  "dvostrano ogledalo",
  "gnušati se",
  "čamac za spašavanje",
  "podsjetiti",
  "pita od jabuka",
  "šetnja",
  "nada",
  "zagrliti",
  "otkriće",
  "plakati",
  "planinski lanac",
  "komedija",
  "želja",
  "gornji kat",
  "životinja",
  "reženi kruh",
  "igrati",
  "električni roštilj",
  "dolje",
  "skretanje",
  "zidni sat",
  "demokrat",
  "banane",
  "Tokio",
  "slonić Dumbo",
  "udaljenost",
  "zalogajnica",
  "kada",
  "tajno skladište",
  "žuč",
  "cvjećar",
  "biskup",
  "šaptač",
  "popis za kupovinu",
  "zaglavlje",
  "bedem",
  "blagajnica",
  "glina",
  "koljenica",
  "bodljikava žica",
  "dotjerano",
  "svemir",
  "žuto",
  "slad",
  "podna svjetiljka",
  "država",
  "drobilica oraha",
  "Bik Koji Sjedi",
  "smirenost",
  "vodovodna cijev",
  "mali prst",
  "sjeverozapad",
  "ulična svjetiljka",
  "dojava",
  "uštedjeti",
  "velikodušno",
  "plin smijavac",
  "kupaonski ručnik",
  "igla za šivanje",
  "mijesiti",
  "bijes",
  "zanimanje",
  "dugometražni film",
  "iza",
  "vrsta",
  "pedijatar",
  "brijanje",
  "kišomjer",
  "red",
  "ispeći palačinke",
  "kravata",
  "Sicilija",
  "nasip",
  "mrežica za kosu",
  "čokoladica",
  "Snjeguljica i sedam patuljaka",
  "NHL",
  "teturati",
  "perilica posuđa",
  "janje",
  "slano",
  "tko",
  "odmorište",
  "Rolling Stones",
  "grupa",
  "djetilć",
  "rezervacija stola",
  "barski stolac",
  "super ljepilo",
  "razočarano",
  "privjesak za ključeve",
  "vaza",
  "pripovjedač",
  "Harry Potter",
  "kava",
  "sluga",
  "kamerman",
  "blago",
  "šubara",
  "papar",
  "svadbena koračnica",
  "vrh",
  "detektor dima",
  "svući",
  "tijesto za kolače",
  "prestići",
  "pripovjetka",
  "šator",
  "duh",
  "džep",
  "udarna bušilica",
  "zubna proteza",
  "pristanište",
  "slagalica",
  "breza",
  "reflektor",
  "Mona Lisa",
  "duhovni",
  "s uzorkom",
  "ledeno doba",
  "arhitekt",
  "kofein",
  "luđak",
  "bljesak",
  "mišolovka",
  "baguette",
  "mikro čip",
  "sportski auto",
  "tretman",
  "vozač",
  "snježna gruda",
  "bijelo",
  "hangar",
  "vozač autobusa",
  "sjeći drva",
  "električni ventilator",
  "kratka majica",
  "body builder",
  "sandala",
  "radio sa satom",
  "centar",
  "pljesak",
  "poezija",
  "sidro",
  "glazbeni sustav",
  "jadno",
  "pobuna",
  "potvrda",
  "ispušne cijevi",
  "božićna svijetla",
  "linija života",
  "okovi",
  "propeler",
  "let",
  "divljina",
  "spojka",
  "labirint",
  "strategija",
  "pjevati",
  "skok u dalj",
  "smrdljiv",
  "polirati",
  "sova ušara",
  "leopard",
  "supružnik",
  "detonirati",
  "gips",
  "kut",
  "humano",
  "metronom",
  "prikupiti",
  "naprstak",
  "stidljiv",
  "hrpa",
  "pomilovanje",
  "cvjetnjak",
  "aluminij",
  "štene",
  "otvarač za boce",
  "zatvarač",
  "kratko",
  "pečeni krumpir",
  "diviti se",
  "šest",
  "Pepeljuga",
  "Mickey Mouse",
  "začinjeno",
  "pupčana vrpca",
  "kineski",
  "vječno",
  "profesionalno",
  "aparat za kavu",
  "kantica za zalijevanje",
  "kosti",
  "sirena za maglu",
  "Crno more",
  "čivava",
  "skočimiš",
  "gradilište",
  "pisaća mašina",
  "eksplozija",
  "vojni",
  "privjesak",
  "motorna pila",
  "ljetno računanje vremena",
  "SOS",
  "zmaj",
  "DVD",
  "barkod skener",
  "kunić",
  "ugravirati",
  "sadržaj",
  "vrećica sa zatvaračem",
  "zvrk",
  "palačinka",
  "gnijezdo",
  "četka",
  "izborno",
  "bombonijera",
  "žena",
  "trapavica",
  "ugasiti",
  "miomiris",
  "prvo",
  "piknik",
  "pločnik",
  "sat",
  "miroljubivo",
  "djetašce",
  "negativno",
  "ludo",
  "gaćice",
  "halucinacija",
  "klamerica",
  "prekidač",
  "mađionarski trk",
  "hibernacija",
  "hrvanje",
  "čovjek",
  "prasak",
  "računalo",
  "kožna jakna",
  "koš za smeće",
  "četka za kosu",
  "šepati",
  "morska trava",
  "omesti",
  "udovica",
  "salata",
  "crkveni miš",
  "kugla",
  "ocean",
  "salon",
  "noćni let",
  "fotografija",
  "krigla",
  "Hinko, Dinko, Vinko",
  "nesretno",
  "um",
  "poni",
  "ručni sat",
  "SIM kartica",
  "oko",
  "njuškati",
  "kovač",
  "samoglasnik",
  "Beethoven",
  "luster",
  "domaćin",
  "zamorac",
  "aerobik u vodi",
  "kvaliteta",
  "panda",
  "žemlja",
  "gramofon",
  "garancija",
  "atletičar",
  "boa",
  "osvajač zlatne medalje",
  "električna gitara",
  "grožđica",
  "traktor",
  "nož",
  "ljepilo",
  "dadilja",
  "zahtijevati",
  "kombinezon",
  "zadnjica",
  "neobičan",
  "razlog",
  "Eiffelov toranj",
  "najbolji",
  "ventilirati",
  "smjer",
  "pospan",
  "avionska karta",
  "skok s motkom",
  "stečaj",
  "vrećica za prašinu",
  "pero",
  "banana",
  "staklenka",
  "zabavljati",
  "Zadar",
  "velika bijela psina",
  "kockica leda",
  "mraz",
  "kontaktne leće",
  "prati zube",
  "izviđač",
  "sveučilište",
  "slatkiš",
  "prst",
  "poslati poljubac",
  "kruh",
  "pokretna vrata",
  "avion",
  "sjever",
  "sklad",
  "zagrabiti",
  "metro",
  "proba",
  "naresci",
  "hod po užetu",
  "plan",
  "benzinska stanica",
  "vanjski",
  "zadrhtati",
  "odostraga",
  "krumpirovo brašno",
  "nekoć",
  "blijedo",
  "noć",
  "opuštanje",
  "astronaut",
  "mucanje",
  "prijenosno računalo",
  "svizac",
  "hobotnica",
  "izlagač",
  "kup Krešimira Ćosića",
  "htjeti",
  "uhvatiti",
  "anakonda",
  "kanu",
  "srećković",
  "alergičan",
  "bubnjevi",
  "čokoladni kolač",
  "morska sol",
  "amputacija",
  "sobarica",
  "živahno",
  "gorjeti",
  "tableta",
  "telegram",
  "proračun",
  "brodska sirena",
  "viza",
  "kreker",
  "brzina",
  "nisko",
  "beba",
  "vožnja",
  "umoran",
  "zmija",
  "iver",
  "traperice",
  "mula",
  "jučer",
  "kazneni udarac",
  "ohrabriti",
  "uragan",
  "polarni medvjed",
  "smaragd",
  "laboratorij",
  "odalamiti",
  "malarija",
  "advent",
  "smicalica",
  "pozitivno",
  "osjećaj",
  "Profesor Baltazar",
  "rola filma",
  "aparatić za zube",
  "Ratovi zvijezda",
  "ljubav",
  "vježba",
  "pozlaćen",
  "njemački ovčar",
  "karling",
  "auto dizalica",
  "hidromasažna kada",
  "krafna",
  "šegrt Hlapić",
  "čajnik",
  "Petak",
  "dragulj",
  "švedski",
  "bicikl",
  "promjena",
  "Božić",
  "mastan",
  "jarak",
  "mačkasto",
  "pustinjak",
  "instinkt",
  "udvostručiti",
  "što",
  "pečat",
  "poluga",
  "samostrel",
  "gromada",
  "puder",
  "autobus",
  "desert",
  "hobit",
  "željezo",
  "osigurano",
  "utrka Formule 1",
  "boja",
  "redovnik",
  "seksi",
  "borba s bikovima",
  "aparat za proizvodnju sladoleda",
  "voće",
  "profesor",
  "prodavač automobila",
  "stremen",
  "Indija",
  "špijun",
  "Djed Mraz",
  "sjeme",
  "osovina",
  "svjetlosni mač",
  "grobar",
  "stjuardesa",
  "mnogi",
  "žetva",
  "roktati",
  "sliniti",
  "odnositi",
  "stog",
  "zaljubljeno",
  "glasački listić",
  "znakovni jezik",
  "kvačilo",
  "rabljeno",
  "lopta za gimnastiku",
  "peludna groznica",
  "dovod",
  "prosuti",
  "svijet",
  "tamo",
  "trik",
  "tvornica",
  "služba za korisnike",
  "novčanik",
  "test",
  "polica za knjige",
  "zamah",
  "začini",
  "suditi",
  "prijatelj",
  "pojačalo",
  "češnjak",
  "Novi Zeland",
  "fantastičan",
  "Badnjak",
  "bilješka",
  "tavica",
  "iluzija",
  "step",
  "demonstacija",
  "misteriozno",
  "obaranje ruku",
  "miris",
  "nula",
  "Hamlet",
  "vodeni balon",
  "iskliznuti",
  "daleko",
  "Dalmatina",
  "razmišljati",
  "riblja juha",
  "Kapetan Kuka",
  "nilski konj",
  "pravila igre",
  "pobijediti",
  "dnevnica",
  "slamka",
  "turbo",
  "crijevo",
  "kartaška igra",
  "vojska",
  "krilo",
  "vješalica za odjeću",
  "lopatica za kuhanje",
  "špricati",
  "faks",
  "gorivo",
  "pokojni",
  "vizir",
  "ton",
  "zvjezdana prašina",
  "eliptično",
  "ručica",
  "sladoled na štapiću",
  "fobija",
  "naglasak",
  "sat s kukavicom",
  "pečenka",
  "kiseli krastavac",
  "sigurnosni remen",
  "kolač",
  "vanzemaljski",
  "pruće",
  "tantrum",
  "naslonjač",
  "greda",
  "teleskop",
  "divno",
  "korov",
  "pogačica",
  "tumač",
  "zanimljivo",
  "pauza za kavu",
  "stalak",
  "prikolica",
  "ispustiti",
  "zamljopis",
  "učitelj",
  "bacati",
  "crv",
  "Marsovac",
  "kocka",
  "bonus",
  "šišmiš",
  "hrvati se",
  "istezanje",
  "salto",
  "spirala",
  "koplje",
  "Tyrannosaurus",
  "bingo",
  "gubica",
  "hrskavo",
  "kobra",
  "džem od malina",
  "gusjenica",
  "rakun",
  "proganjati",
  "karate",
  "koliba",
  "dadilja",
  "poplav",
  "zračni madrac",
  "lažno",
  "depresivno",
  "biologija",
  "džudo",
  "tetrapak",
  "industrija",
  "nogometaš",
  "Turska",
  "muha",
  "šampinjon",
  "hladnjak",
  "tijesno",
  "bod",
  "upitnik",
  "tinejdžer",
  "nogomet",
  "sunčeva svjetlost",
  "nastavi",
  "blagoslov",
  "škrinja s blagom",
  "lisnato tijesto",
  "naočale",
  "otok",
  "svijetlo plavo",
  "ozbiljno",
  "uputiti",
  "lutrija",
  "tenk",
  "zaobići",
  "Uskršnji otoci",
  "kroz vrijeme",
  "precizno",
  "pranje",
  "otporno",
  "sposobnost",
  "poboljšanje",
  "falda",
  "zavist",
  "helikopter",
  "istočnjački",
  "zabavni park",
  "protest",
  "snaga",
  "zaviriti",
  "prevencija",
  "istraživanje",
  "čin",
  "strašljivo",
  "dozvola za građenje",
  "mlijeko",
  "kockanje",
  "ovdje",
  "srednje veličine",
  "srp",
  "biljeg",
  "jazz",
  "ograda",
  "grub",
  "psovati",
  "djetelina",
  "znanstvenik",
  "kutija za alat",
  "jastuk",
  "salata s piletinom",
  "navigacija",
  "povijest",
  "moj",
  "jaje",
  "ulazna vrata",
  "prijestupna godina",
  "usporediti",
  "borova šišarka",
  "mini suknja",
  "vijesti",
  "debata",
  "brat",
  "svjetionik",
  "ostatak",
  "njemački",
  "pješački prijelaz",
  "suradnja",
  "ledena santa",
  "dionice",
  "kamen",
  "pračovjek",
  "žica",
  "pecivo",
  "francuski ključ",
  "obrati",
  "jacuzzi",
  "ljeto",
  "lov",
  "čepići za uši",
  "crno",
  "leptir",
  "maltezer",
  "zapamtiti",
  "svježe",
  "pljeskavica",
  "ravnalo",
  "Kleopatra",
  "noćna svjetiljka",
  "kopač",
  "stranica",
  "štake",
  "bez rukava",
  "kišna kapljica",
  "vilenjak Djeda Mraza",
  "vrbina maca",
  "Auto-rally",
  "ribarnica",
  "tricikl",
  "zapanjujuć",
  "gacati",
  "peraja",
  "staklenik",
  "pohlepno",
  "kavez",
  "poljubac",
  "majčinsko",
  "lijevano željezo",
  "naše",
  "škola",
  "partner",
  "televizor",
  "bezvremensko",
  "trojke",
  "štule",
  "lice",
  "autentično",
  "konac",
  "antilopa",
  "ragbi",
  "proviriti",
  "zamahnuti",
  "isprašivač tepiha",
  "ugušiti",
  "potkrovlje",
  "rasti",
  "rog",
  "smrad",
  "paun",
  "sigurno",
  "kabel",
  "praznina",
  "golub pismonoša",
  "hidratantna krema",
  "vlakno",
  "sultan",
  "vlada",
  "zviždaljka za pse",
  "kosilica",
  "potpis",
  "Joker",
  "vitko",
  "meditirati",
  "jahta",
  "frak",
  "nezaposlen",
  "kuhar",
  "scena",
  "bacanje diska",
  "točka",
  "ispravno",
  "uskoro",
  "mikrofon",
  "napitak",
  "lokot s brojčanom kombinacijom",
  "balon",
  "okrutno",
  "jagode",
  "rođak u drugom koljenu",
  "uže",
  "iskakalica",
  "korice",
  "padobranac",
  "kruto",
  "SMS poruka",
  "prekosutra",
  "kamp",
  "anđeo",
  "draguljarnica",
  "ulog",
  "vagon",
  "lopta",
  "kantina",
  "nokautirati",
  "Break-dance",
  "trudnoća",
  "sovuljaga",
  "košarka",
  "ispred",
  "beskućnik",
  "povez za oko",
  "pljusak",
  "nabusit",
  "ljetna pozornica",
  "odan",
  "video igra",
  "struk",
  "omotnica",
  "štednjak",
  "šal",
  "stipendija",
  "samo",
  "vrećica",
  "vruće",
  "vrata",
  "daska za surfanje",
  "Sydney",
  "zlatni zub",
  "pješačenje",
  "zračenje",
  "rezervacija",
  "Snoopy",
  "astronom",
  "pred",
  "staviti",
  "brana",
  "bačva",
  "gljiva",
  "rudnik",
  "potres",
  "noj",
  "model aviona",
  "kanalizacija",
  "kapetan leta",
  "muževan",
  "svrab",
  "truba",
  "bar kod",
  "zamrzivač",
  "putnik",
  "žar",
  "popis",
  "katran",
  "otmica",
  "Gardaland",
  "kosa",
  "nakit",
  "papiga",
  "zrak",
  "Minnie Mouse",
  "opalo lišće",
  "naprijed",
  "boca",
  "narančasto",
  "naslovnica",
  "bundeva",
  "glasine",
  "štrukla",
  "recitirati",
  "džungla",
  "Igre prijestolja",
  "pelena",
  "boćanje",
  "kućica za psa",
  "rukovati se",
  "žongler",
  "nebitno",
  "nabor",
  "izdržljivost",
  "hlače",
  "izazov",
  "krajolik",
  "klizaljke",
  "poštar",
  "presaviti",
  "gostionica",
  "zlostavljati",
  "kostur",
  "čarolija",
  "padobran",
  "puno",
  "desno",
  "formalno",
  "narukvica",
  "dizalo",
  "puslice",
  "slonovača",
  "pavijan",
  "suživot",
  "bajt",
  "seoska luda",
  "rezervno",
  "četvrtak",
  "hinduizam",
  "složenac",
  "sretno",
  "noćna životinja",
  "nalivpero",
  "mutacija",
  "tipkovnica",
  "vraćati",
  "nit",
  "ime",
  "dihalica",
  "karamela",
  "pokunjen",
  "kompas",
  "urediti",
  "kompozitor",
  "zastupnik",
  "sisavac",
  "oštrica",
  "podrum",
  "bas",
  "bezopasan",
  "ispušni",
  "bambus",
  "toalet",
  "rad",
  "galerija",
  "nenormalan",
  "gram",
  "nečuveno",
  "besprijekorno",
  "kopito",
  "pakleni dan",
  "stegnuti",
  "jetra",
  "baterija",
  "roman",
  "cimet",
  "škripa",
  "podno grijanje",
  "slanina",
  "pismo",
  "teorija",
  "mitariti",
  "prevoditelj",
  "majmun",
  "lav",
  "štakor",
  "političar",
  "prometni znak",
  "medenjak",
  "brvnara",
  "kupaonica",
  "mineralna voda",
  "curry začin",
  "buha",
  "budala",
  "lonac",
  "dokument",
  "džem od brusnica",
  "student",
  "Morseov kod",
  "brdo",
  "Vransko jezero",
  "maska",
  "bitka",
  "doping test",
  "roditeljski dopust",
  "tvornica papira",
  "Cezar",
  "foto knjiga",
  "spasiti",
  "zebra",
  "seljačina",
  "pobjeći",
  "oklada",
  "nestati",
  "Facebook",
  "svjetiljka",
  "strnište",
  "pano",
  "podbačaj",
  "biser",
  "dječji vrtić",
  "ljigavo",
  "tepih",
  "zahvala",
  "kontrolor parkiranja",
  "policija",
  "smrzavanje",
  "samoposluga",
  "voda",
  "klackalica",
  "zanijeti se",
  "dlakavo",
  "produžni kabel",
  "podoćnjaci",
  "kasati",
  "jackpot",
  "dakle",
  "taco",
  "oporuka",
  "pladanj",
  "gimnastika",
  "rezervna guma",
  "piće",
  "reflektor",
  "kič",
  "vodoinstalater",
  "razmjena dobara",
  "šmrcavost","lim za pečenje",
  "gumena igračka",
  "riba",
  "rubin",
  "izmisliti",
  "piškiti",
  "lutati",
  "retriver",
  "abakus",
  "tijelo",
  "pečena purica",
  "krevet",
  "tupe",
  "kokice",
  "vratnica",
  "poslijepodne",
  "parni stroj",
  "plimni val",
  "luka",
  "muffin",
  "Robin Hood",
  "buba",
  "prorok",
  "bez laktoze",
  "križ",
  "pomrčina",
  "Ralje",
  "čipka",
  "govoriti",
  "Ponedjeljak",
  "opterećenje",
  "grubijan",
  "ogovaranje",
  "mačka",
  "komplicirano",
  "karta",
  "disko",
  "staza",
  "lokot za volan",
  "vrabac",
  "krovni nosač",
  "lijana",
  "vilin konjic",
  "hrenovka u tijestu",
  "orao",
  "istok",
  "Danska",
  "brusni papir",
  "Osijek",
  "zavidan",
  "cvasti",
  "brz na obaraču",
  "viseća mreža za ležanje",
  "kanal",
  "nužno",
  "voditi",
  "pomoćni kotači",
  "grm",
  "bejzbol",
  "ogrebotina",
  "Velebit",
  "porozno",
  "dreadlocksi",
  "stražnjica",
  "razumijevanje",
  "opijenost",
  "ključ",
  "Kralj Lavova",
  "kiselo vrhnje",
  "magija",
  "povratak",
  "prečac",
  "ravnatelj",
  "žeti",
  "jež",
  "prisilno slijetanje",
  "stajati",
  "astronaut",
  "na",
  "komunist",
  "krema za sunčanje",
  "gledati",
  "buka",
  "sigurnosni sustav",
  "fizioterapeut",
  "piramida",
  "ponos",
  "album",
  "vila",
  "limenka",
  "djeveruša",
  "pacijent",
  "divlja životinja",
  "ukloniti",
  "klima",
  "bezalkoholno",
  "teško",
  "osmijeh",
  "stijeg",
  "ispisati",
  "proljeće",
  "povratno putovanje",
  "dimnjak",
  "povratno putovanje",
  "plavo",
  "porobiti",
  "šmrkanje",
  "iskupljenje",
  "električna mješalica",
  "pastrva",
  "emotivan",
  "stabilan",
  "vještina",
  "šalica za kavu",
  "matematika",
  "ventilator",
  "oštro",
  "prolom oblaka",
  "otrov",
  "organizator vjenčanja",
  "značajan",
  "mirotvorac",
  "vilica",
  "sljez",
  "slatko",
  "stolica",
  "svitak",
  "živi pijesak",
  "čips",
  "kaos",
  "obala",
  "Alpe",
  "vadičep",
  "egocentrično",
  "nevjesta",
  "srednji prst",
  "štap",
  "autocesta",
  "Božićni puding",
  "čađa",
  "rotkvica",
  "uzeti",
  "crkveno zvono",
  "jecati",
  "agent za nekretnine",
  "prašina",
  "daska",
  "zarada",
  "složeno",
  "lomača",
  "čuveno",
  "zaustaviti",
  "izoštriti",
  "ogledalo",
  "umjetnik",
  "kristalna kugla",
  "mango",
  "mučiti",
  "zaigrano",
  "pogodak",
  "bilo pa prošlo",
  "debljina",
  "pudlica",
  "stoka",
  "zvonjava",
  "razvrstati",
  "žičani instrument",
  "Severina",
  "dijagonala",
  "vremeplov",
  "takvo",
  "električna grijalica",
  "tjelovježba",
  "Azija",
  "odrijemati",
  "novac",
  "zemlja",
  "ukrotiti",
  "Himalaja",
  "centilitar",
  "zamrznuto",
  "zahtjev",
  "kockice leda",
  "as",
  "palac",
  "kornjača",
  "pedikura",
  "kongresmen",
  "kombi",
  "sladoled",
  "kantor",
  "kazališna ulaznica",
  "stadion",
  "tajnica",
  "porođaj",
  "Ivo Gregurević",
  "ulični svirač",
  "smijeh",
  "utrka",
  "agencija za oglašavanje",
  "morska voda",
  "na propuhu",
  "paluba",
  "Posejdon",
  "upozorenje",
  "pijuk",
  "grozničav",
  "soda",
  "češalj",
  "vakum",
  "pečeno jaje",
  "Einstein",
  "lizalica",
  "dodatak",
  "sponzor",
  "zvončići",
  "samo",
  "vlak",
  "oklijevati",
  "oraspoložiti",
  "tehnologija",
  "posrnuti",
  "ljuljati",
  "čili",
  "željeno",
  "pjesma",
  "štap za hodanje",
  "katapult",
  "pepeljara",
  "pločica",
  "poker",
  "vjetrobran",
  "nakit za pupak",
  "pila",
  "šipke",
  "koljeno",
  "trgovina obuće",
  "blizanci",
  "predvorje",
  "olimpijske igre",
  "put",
  "crni papar",
  "grgljati",
  "kineska hrana",
  "kupaći kostim",
  "akne",
  "lopatica",
  "priručnik s uputama",
  "mikroskop",
  "neukusno",
  "skraćenica",
  "žlica",
  "klimnuti glavom",
  "kartica",
  "organski uzgoj",
  "tiho",
  "lažne trepavice",
  "detektor metala",
  "ljubičasto",
  "sumaglica",
  "teniska mreža",
  "jeftino",
  "Ljepotica i zvijer",
  "margarin",
  "blok",
  "proteza",
  "borba",
  "rukavica za boks",
  "pješčana oluja",
  "naravno",
  "praćka",
  "stjenica",
  "Dan neovisnosti",
  "TV voditelj",
  "dosadno",
  "komet",
  "jutarnja kava",
  "koraljni",
  "zgodan",
  "iznenađenje",
  "plovilo",
  "zlo",
  "uganuti",
  "cmizdriti",
  "ukočenost",
  "umjetnici",
  "zaboraviti",
  "škamp",
  "bobica",
  "osa",
  "poljoprivrednik",
  "rame",
  "parkirna kazna",
  "guma",
  "glačati",
  "bežično",
  "genije",
  "utjecaj",
  "pijanist",
  "insekticid",
  "kraljestvo",
  "oluja",
  "kolica",
  "zabava",
  "lešinar",
  "krvavica",
  "aluminijska folija",
  "Živjeli!",
  "zid",
  "štipati",
  "Zlatokosa",
  "srce",
  "privlačnost",
  "dovitljivo",
  "orijentacija",
  "površno",
  "skijati",
  "zalagaonica",
  "lubenica",
  "drevno",
  "dirigent",
  "slikar",
  "klon",
  "opatica",
  "kako",
  "gutljaj",
  "ružičasto",
  "samouvjeren",
  "upravljati",
  "maraton",
  "pokretna traka za trčanje",
  "kao",
  "klimatizirano",
  "kišobran",
  "podnijeti",
  "paket",
  "entuzijasično",
  "telefonska sekretarica",
  "trčanje sa preponama",
  "alarm",
  "interval",
  "autopilot",
  "osigurač",
  "romobil",
  "jedanaesterac",
  "Mjesec",
  "trenje",
  "tost",
  "napredno",
  "spaliti gume",
  "manjina",
  "uzgajivačnica",
  "pjenušava kupka",
  "glazba",
  "objasniti",
  "motorne sanjke",
  "retrovizor",
  "pregledati",
  "svijest",
  "terasa",
  "barmen",
  "portret",
  "pjena",
  "Ana nabra par banana",
  "siromašno",
  "europski",
  "ljubiti",
  "lončić za kavu",
  "pleme",
  "hrast",
  "žensko",
  "prljaga",
  "akord",
  "bjesnoća",
  "krušne mrvice",
  "vezica",
  "tamno",
  "predgrađe",
  "monitor otkucaj srca",
  "naziv tvrtke",
  "sporazum",
  "ljepota",
  "baletna plesačica",
  "vjenčanje",
  "zdrobiti",
  "čekić",
  "ploča za igru",
  "Asterix",
  "decilitar",
  "USB uređaj",
  "invalidska kolica",
  "povezati",
  "pire",
  "bolje",
  "ravnoteža",
  "zbrajanje",
  "stolni tenis",
  "škare",
  "trčanje",
  "knjiga pripovjetaka",
  "korjenje",
  "ogrlica",
  "Pješčani čovjek",
  "pulover",
  "šarlatan",
  "komad",
  "usko",
  "besplatno",
  "nastavak",
  "kihati",
  "gangster",
  "srebrni metak",
  "antivirusni program",
  "zvonce",
  "ludilo",
  "folija",
  "državni tajnik",
  "ubrus",
  "sladić",
  "užina",
  "šivaća mašina",
  "Poljska",
  "kaskader",
  "provjeriti",
  "nositi",
  "kavana",
  "policijski pas",
  "imanje",
  "goropadnica",
  "toplo",
  "učenik",
  "Sherlock Holmes",
  "gumene čizme",
  "gazirano piće",
  "ležaj",
  "ples",
  "francuz",
  "flauta",
  "mahovina",
  "Kilimanjaro",
  "batler",
  "predsjednik",
  "teroristi",
  "prozirna folija",
  "poletuša",
  "Zlatni rat",
  "silos",
  "daska za glačanje",
  "haker",
  "krstiti",
  "mirisno",
  "biskvit",
  "prsni koš",
  "prizor",
  "proglasiti",
  "odvikavanje",
  "sklonište",
  "narudžba",
  "biciklizam",
  "dalekovod",
  "duboko",
  "kamion",
  "povoljno",
  "alergija",
  "Kolumbo",
  "slijetanje",
  "prognostičar",
  "bezopasno",
  "djed",
  "koji",
  "koma",
  "mrzlo",
  "šminka",
  "božićna čestitka",
  "Mozart",
  "umirovljenik",
  "stati",
  "Europska Unija",
  "mulj",
  "jutarnji stres",
  "fantom",
  "tržište",
  "podvezica",
  "krug",
  "zvono",
  "rezervoar",
  "podbradak",
  "posijediti",
  "uzbudljivo",
  "podvala",
  "kolesterol",
  "pluća",
  "komarac",
  "smeđe",
  "kristal",
  "nebo",
  "porculan",
  "označiti",
  "disco ples",
  "gušterača",
  "ljuto",
  "zamrznuti",
  "fontana",
  "usna školjka",
  "najmlađe dijete",
  "trbušni mišići",
  "Ružno pače",
  "hodočasnik",
  "dužina",
  "kino",
  "temperatura",
  "balet",
  "plišana igračka",
  "podzemna voda",
  "otac",
  "Franjo Tuđman",
  "car",
  "jesen",
  "kuglice",
  "napušteno",
  "ananas",
  "noćni klub",
  "pekač kruha",
  "taksi",
  "bok",
  "plećka",
  "nemasno",
  "Shakespeare",
  "stakleno oko",
  "zatvorenik",
  "tetovaža",
  "nervozno",
  "tuna",
  "rosa",
  "kriška",
  "električna žica",
  "božićni poklon",
  "skratiti",
  "naslov",
  "lunapark autić",
  "podcijeniti",
  "potres mozga",
  "hladno",
  "gumica za kosu",
  "automat za kockanje",
  "igra",
  "neriješen",
  "milja",
  "obilazak",
  "bazen",
  "flaster",
  "Wi-Fi",
  "ventil",
  "pol",
  "Elvis Presley",
  "znak",
  "zdravo",
  "bendžo",
  "dobiti",
  "recikliranje",
  "jarbol",
  "gdje",
  "ispaziti jezik",
  "pjevač",
  "čisto",
  "djevojka",
  "rat",
  "pokućstvo",
  "Smrt",
  "staro",
  "tombola",
  "gumeni bombon",
  "moć",
  "zapanjeno",
  "srebrna medalja",
  "narednik",
  "daljinski upravljač",
  "oprati kosu",
  "kaciga",
  "kozji sir",
  "elektrana",
  "oskudno",
  "suparnik",
  "pejzaž",
  "pantera",
  "prekrivač",
  "kesten",
  "prodavač",
  "noć vještica",
  "prežderati se",
  "okidač",
  "rumenilo",
  "električno",
  "kokošja juha",
  "plastelin",
  "mršaviti",
  "ledeno",
  "kampiranje",
  "slavna osoba",
  "torba",
  "gušter",
  "kobasica",
  "džamija",
  "ključna kost",
  "tamponi",
  "ogromno",
  "pila za metal",
  "osjetljivost",
  "oaza",
  "violonist",
  "čopor",
  "ribarstvo",
  "tegljač",
  "sigurnosna igla",
  "silicij",
  "Njemačka",
  "Veliki prasak",
  "instrument",
  "prometna gužva",
  "Croatia Airlines",
  "zašto",
  "lem",
  "traka",
  "kopar",
  "usamljen",
  "zbunjujuće",
  "ubojica",
  "trkaća staza",
  "jasno",
  "vjeverica",
  "električar",
  "odvjetnik",
  "slijep",
  "utičnica",
  "krivotvoritelj",
  "mobitel",
  "paprika",
  "obožavatelj",
  "dvorište",
  "ljetna haljina",
  "straža",
  "neuljudan",
  "kamionet",
  "vidovnjak",
  "kuguar",
  "Ernest Hemingway",
  "bijeg",
  "hipoteka",
  "limun",
  "aktovka",
  "morski krastavac",
  "domaćica",
  "kupka",
  "uzdah",
  "parlament",
  "grinja",
  "priča o duhovima",
  "malj",
  "noćni obrok",
  "deblo",
  "teretni brod",
  "rotirati",
  "žvakaća guma",
  "svjetla za maglu",
  "težak",
  "čavao",
  "konus",
  "svjećnjak",
  "lik",
  "otopiti",
  "Blue-ray",
  "drugi",
  "diktator",
  "kuglanje",
  "hram",
  "tobolac",
  "nemilosrdno",
  "bakterijsko",
  "zimsko",
  "naljepnica",
  "krajnik",
  "bedro",
  "sjeći",
  "ćup",
  "krtica",
  "kapljica",
  "Sibir",
  "vitez",
  "obnoviti",
  "stražnja vrata",
  "pitalica",
  "rukavice",
  "vatrogasac",
  "hranilica za ptice",
  "vrijeme",
  "glumica",
  "odmor",
  "vrtlar",
  "studij",
  "teren za golf",
  "kraj",
  "vrč",
  "vodootporno",
  "recept",
  "krdo sobova",
  "navalažiti",
  "ideja",
  "tražiti",
  "žedno",
  "znatiželjno",
  "raspasti se",
  "zečić",
  "vata",
  "nos",
  "otvoreno",
  "polog",
  "klizanje",
  "južni pol",
  "ruž za usne",
  "Crvenkapica",
  "preplanulost",
  "kupaće gaće",
  "uskogrudan",
  "žmigavac",
  "terminal",
  "zubić vila",
  "uskogrudan",
  "napustiti",
  "kora od banane",
  "naušnica",
  "kabriolet",
  "liga",
  "termosica",
  "kontakti",
  "samostan",
  "film",
  "snažno",
  "mrkva",
  "milijunaš",
  "čovječanstvo",
  "bez svijesti",
  "aligator",
  "veslo",
  "ostali",
  "borac",
  "svijeća",
  "piercing",
  "lovac",
  "ladica",
  "glas",
  "križaljka",
  "nadogradnja",
  "gumica",
  "zadržati"
]
