module.exports = [
  'riječ',
  'snažan',
  'mikroekonomija',
  'dugačak',
  'atribut',
  'ime',
  'imenica',
  'inicijal',
  'izvođenje',
  'alijansa',
  'sporazum',
  'dogovoriti',
  'odgovoriti',
  'mazohistički',
  'ljubomoran',
  'masnica ispod oka',
  'udarac',
  'strujni udar',
  'zanemariti',
  'razuvjeriti',
  'ispovjediti',
  'izaslanik',
  'darivatelj',
  'čudak',
  'laik',
  'leptir mašna',
  'kravata',
  'automobilska industrija',
  'zabranjeno pušenje',
  'maskica za mobitel',
  'bratić',
  'zaustavna traka',
  'izbezumiti',
  'novčani dobitak',
  'gubitnički listić',
  'mlado meso',
  'povrće',
  'malen',
  'velik',
  'zajednica',
  'zajedno',
  
]
